spring:
  application:
    name: notification-system*
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true


server:
  port: ${APP_PORT:8080}
